#!/bin/bash
#Flush existing rulrs and set default policy to enable Incoming and outgoing trafic
iptables -F
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT

#Allow incomming SSH traffic from the UbuntuServer MAC address
iptables -A INPUT -m mac -- mac-source 08:00:27:6E:3D:57 -p tcp -- dport 22 -j ACCEPT
# Block icoming SHH trafic from other MAC addresses
iptables -A INPUT -p tcp -- dport 22 -j DROP

# Block incoming and outgoing HTTP port 80 traffic:
iptables -A OUTPUT -p tcp -- dport 80 -j DROP
iptables -A INPUT -p tcp -- dport 80 -j DROP

#block incomming and outgoing telnet trafic
iptables -A INPUT -p tcp -- dport 23 -j DROP
iptables -A OUTPUT -p tcp -- dport 23 -j DROP

#Allow incomming and outgoing HTTPS port 443 trafic
iptables -A INPUT -p tcp -- dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp -- dport 443 -j ACCEPT

# Block incoming and outgoing HTTP port 80 traffic:
iptables -A OUTPUT -p tcp -- dport 80 -j DROP
iptables -A INPUT -p tcp -- dport 80 -j DROP

#block incomming and outgoing telnet trafic
iptables -A INPUT -p tcp -- dport 23 -j DROP
iptables -A OUTPUT -p tcp -- dport 23 -j DROP

#Allow incomming and outgoing HTTPS port 443 trafic
iptables -A INPUT -p tcp -- dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp -- dport 443 -j ACCEPT

#Block incomming ICMP ping requests
iptables -A INPUT -p icmp -- icmp-type echo-request -j DROP

#Block incoming ICMP traceroute requests
iptables -A INPUT -p icmp -- icmp-type echo-reply -j DROP

#save the firewall rules
iptables-save > /etc/iptables/rules.v4
